### PR TITLE
Add tag command

### PR DESCRIPTION
**Pull request by oss92**
## Details
Add command to tag Lambdas.
```bash
claudia tag --tag "Team=onboarding,Project=amarillo
```

### PR checklist
- [x] Tag command

### CODE REVIEW

**Comment by gojko** [comment]
Hi,

this looks very good -- please add an automated test to the spec dir, so that others don't break your code when changing it in the future, and i'll merge it in.

**Comment by oss92** [comment]
I will add tests to the spec dir 👍

**Comment by oss92** [comment]
Added tests and rebased.

**Comment by gojko** [comment]
thanks!

**Pull request merged**
