### PR TITLE
Add support for Cognito User Pool Authorizers

### PR DESCRIPTION
**Pull request by paulftw**
I know this lacks specs/tests and my coding style is probably a bit off the project's standards, but based on my experiments this is all it takes to support the Cognito Authorizer. I hope it'll inspire someone.

### CODE REVIEW

**Comment by paulftw** [comment]
Now it seems to actually work. Example usage is:

```
api.registerAuthorizer('CognitoAuthorizer', {
	providerARNs: ['arn:aws:cognito-idp:us-west-2:<SOMEDIGITS>:userpool/us-west-2_POOL-ID']
});

api.post('/lockedMessages', request => {
  return doSomethingUseful()
}, { cognitoAuthorizer: 'CognitoAuth' })
```

**Comment by gojko** [comment]
Hi,

It would be great if you could create a version of the [custom authorizers test](https://github.com/claudiajs/claudia/blob/master/spec/custom-authorizer-integration-spec.js) for cognito pools. That's the key thing missing for me to be able to maintain this code going forward.

You can run just your tests by using 

```
npm test -- filter=testName
``` 
for example, if the top of your spec file has `describe('cognitoAuthorizer', function () {`, then 

```
npm test -- filter=cognitoAuthorizer
``` 
(note the space between `--` and `filter`)

**Comment by paulftw** [comment]
Sure, will do over next week or two

**Comment by gojko** [comment]
i'm closing this due to lack of activity. if someone wants to pick it up and add the tests later, please reopen the pull request.

**Comment by gojko** [comment]
Cognito support is now on NPM as 2.9.0

**Pull request closed without merging**
