### PR TITLE
fix missing tokenCodeFn

### PR DESCRIPTION
**Pull request by gregory**
I was missing the [tokenCodeFn](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ChainableTemporaryCredentials.html) and allow to pass mfa serial through environment variable.

### CODE REVIEW

**Comment by gojko** [comment]
Hi, instead of readline, let's make this another command line argument?

**Comment by gregory** [comment]
What about I update to have both, so that it ll fallback to readline if not present in arguments?

**Comment by gojko** [comment]
that sounds ok to me.

**Comment by gregory** [comment]
addressed your suggestion @gojko ! Let me know if you need anything else. 
Cheers.

**Comment by gojko** [comment]
hi - thanks for this, looks good. I will test and merge over the weekend.

**Comment by gojko** [comment]
Hi - I merged your code and tried to add some specs around it so we can maintain it easier. can you please try if this branch still works for you: https://github.com/claudiajs/claudia/tree/gregory-fix_bug_with_mfa 

if it does what you need, we can merge everything into master

**Comment by gregory** [comment]
sorry for the delay @gojko  - that was a good idea. 
Code is cleaner & still works for me. 
Thanks, let me know if i can help with anything else.

**Comment by gojko** [comment]
@gregory thanks, will release this later today then

**Comment by gojko** [comment]
I can't publish this yet because the current aws-sdk release breaks claudia, I've reported a bug there and waiting on them to release it. as soon as that's done, I'll re-run the tests again and push a new release out

**Comment by gregory** [comment]
wow - crazy - can you link the bug you reported so that we can track status here? 
Thanks for the head's up!

**Comment by gojko** [comment]
@gregory the bug was https://github.com/aws/aws-sdk-js/issues/2588. I released claudia 5.4.2 just now, with your patch, so upgrading to the latest version should have this PR merged in

**Pull request merged**
