### PR TITLE
Add CLI options to create a function as a member of a VPC.

### PR DESCRIPTION
**Pull request by royreiss**
See #17 for more information.

### CODE REVIEW

**Comment by phips28** [comment]
We are using aws-cli to configure vpc's and security group. Its easy to configure in the package.json and you can always update the config. 
Not only in the 'create' process of claudia. 

We use the policy folder and the options for claudia create. 

Example of my package.json (pruned unrelated stuff ;))
https://gist.github.com/phips28/6db2f9a4ca59f7a5ed81241a8bf9af70

So I dont see the benefit of this PR ;) 
IMHO! maybe others need it. Just my 2 cents.

**Comment by royreiss** [comment]
Hey - Thanks for the feedback.  

The package.json idea is interesting, but that same logic could be applied to everything short of deploying the function.  Any tweaks such as the `--set-env` flag could be made after the fact with homebrew scripts, but the benefit of building it into Claudia comes from having it done consistently and knowing the method has been tested.

As for the notion of changing the config after the initial creation I could see also adding the same VPC flags to `claudia update` as beneficial for the same reason.  It would reduce the overhead of having to homebrew scripts.  Not because homebrewing any single script is a huge undertaking on its own, but because providing it gives consistency and saves time in aggregate.

**Comment by gojko** [comment]
This is now on NPM as 2.5.0, thanks!

**Comment by royreiss** [comment]
Thank you! and thanks for the fast response.

**Pull request merged**
