### PR TITLE
Cleanup after deploy: remove tmp folder + zip

### PR DESCRIPTION
**Pull request by phips28**
- after the zip task finished => remove the tmp folder
- after deployment => remove zip
- on create: remove empty npm log file from tmp

### CODE REVIEW

**Comment by gojko** [comment]
the temp files (and npmlog in particular) tend to be very helpful when things blow up. npm log is empty if everything works OK, which is why it seems useless. 

By forcing the code to remove everything as it goes along, we'd lose valuable troubleshooting info. Instead, I suggest doing the removals as the last step of create and update. that way, if something blows up meanwhile, the files stay. if everything works OK, they'll get removed.

**Comment by phips28** [comment]
thats true.
- the last commit does not delete the tmp folder on error while zipping
- npmlogs will stay there if an error occurs.

**Comment by gojko** [comment]
I'd rather just leave everything and remove at the end of create/update. in that case the zipdir function doesn't need to change at all, and we know that if there's an error, it will bail before that. I plan to work on supporting lambda uploads through s3 next week, so that will be a nice chance to add the removal of temp files as well to the end of create/update. I'll close this pull request meanwhile without merging, because I'll just integrate that functionality differently.

**Comment by gojko** [comment]
I've pulled your changes in, and merged manually. This will go out on the next release (1.8.1) - it probably won't show here as merged because I had to manually copy the files to avoid conflicts with some other changes. Thanks for working on this!

**Comment by phips28** [comment]
Ok cool! Thx

mfg,
Philipp Holly

**Comment by gojko** [comment]
1.9.0 is now on NPM with these changes. see https://claudiajs.com/news/2016/09/21/claudia-1.9.0.html for more info

**Pull request closed without merging**
