### PR TITLE
Adds support for specifying an authorizer for API methods

### PR DESCRIPTION
**Pull request by thadd**
This PR adds support for specifying the authorizer that should be used for API methods. 

```javascript
  api.post("/myaction", function (request) {
    // ...
    return "OK";
  }, {authorizerId: 'abcdef'})
```

This is still a work in progress and only works if the authorizer has already been created. It requires you to pull the authorizer ID from the AWS console. Ideally we should also add support for creating/linking the authorizer lambda to the API via Claudia and potentially a name-based reference rather than raw ID. This also doesn't have tests in place yet.

### CODE REVIEW

**Comment by gojko** [comment]
Hi,

I started to look into this. From what I can understand in the docs, AuthorizerId seems to be tied to a particular rest API. Am I reading this wrong? (eg what are you setting for the authorizer ID?)

If the authorizer ID is tied to the rest API, then we should probably automate the creation of the authorizer from a Lambda function as well.

**Comment by thadd** [comment]
Yes, that's correct. I've been working around that issue a bit by first creating the API using Claudia, then adding the authorizer, then adding the `authorizerId` option. I agree it's clunky and would be much better entirely within Claudia.

The ID I'm using is the one returned from `APIGateway.createAuthorizer` and it you're correct that it can't exist without an existing REST API.

Any thoughts on the best way to integrate into Claudia? I'm happy to help, but still very new to the Claudia code base.

**Comment by gojko** [comment]
I guess the key question is how tightly coupled is an authorizer to an API? Does it make sense to use a single authorizer Lambda for multiple APIs? If so, I can make it so that the authorizer configure expects a lambda name, and then register it as an authorizer. If authorizers are tightly coupled with APIs (so one lambda authorizer would be valid only for one API) then it's probably better to provide a JS function, and have Claudia create both the authorizer Lambda and register it with the API.

**Comment by thadd** [comment]
I think there's a fair number of use cases for the authorizer to not be tightly coupled to a single API. In our specific case we're using a custom authorizer to validate a JOT token and I could see it being used it across multiple APIs (or just called from other lambdas) even though we're not currently doing that.

**Comment by gojko** [comment]
so would specifying a lambda name or ARN be a good way to implement your needs (so Claudia would create the authorizer ID when deploying the API)?

**Comment by thadd** [comment]
Yeah, that would be ideal. If I could just specify something like `authorizerName: "my-lambda"`, that would be perfect. ARN would work too, but the advantage of using just the name is that the same codebase could be used for deployment to different accounts if we go by name.

**Comment by gojko** [comment]
Hi,

sorry for the radio silence, I had to catch up with a lot of recent work. I'm writing the custom auth solution that would allow you to specify the lambda name and an authorization header (identity source). There are still a few edge cases to deal with, such as changing the header value during update, but it's coming together. I should be able to push out a new claudia version in a few days with this support. 

I'll close this PR meanwhile because the code is significantly different so there's no point in merging it.

**Comment by thadd** [comment]
Thanks @gojko, looking forward to it!

**Comment by gojko** [comment]
@thadd I finally have a new version out, that should allow you to set what you need. Use the latest versions of api builder (1.6.0) and claudia (1.7.1) and you should be able to define the authorizer easily, such as this:

```js
api.registerAuthorizer('myAuth', {lambdaName: 'some-lambda-name'});
```

then you can just specify it as an authorizer in a method:

```js
api.get('/', function (r) {/* some processing */ }, { customAuthorizer: 'myAuth' })
```

Check out the [docs](https://github.com/claudiajs/claudia-api-builder/blob/master/docs/api.md#using-custom-authorizers) for more info, and the [custom authorizers example](https://github.com/claudiajs/example-projects/tree/master/custom-authorizers) for a working example

**Comment by thadd** [comment]
Awesome, thanks @gojko!

**Pull request closed without merging**
