### PR TITLE
Broader authorization support

### PR DESCRIPTION
**Pull request by dhackner**
Allow linking of existing authorizers and cognito user pool authorization.

### CODE REVIEW

**Comment by dhackner** [comment]
@gojko - I know I should add tests, will get to them ASAP, but in the meantime now this is here for anybody else who is blocked.

**Comment by gojko** [comment]
make sure that the pre-existing authorizer does not get removed during deployment. IDs are specific to an API (unlike ARNs) and Claudia will clean them up during updates

**Comment by dhackner** [comment]
It doesn't clean them up because the API isn't fully removed; the root `/` stays there.

**Comment by gojko** [comment]
@dhackner i'm pretty sure it's cleaning up existing authorizers, check this line: https://github.com/claudiajs/claudia/blob/master/src/tasks/register-authorizers.js#L95

I didn't have time to make it check for existing authorizers and compare existing configuration to the requested config, then merge differences, so I just remove all the authorizers and rebuild them from scratch. I might do a diff in the future, once I have time to look into this properly. 

if you want to preserve auhorizer IDs, you'll have to implement that as well.

**Comment by gojko** [comment]
c

**Comment by dhackner** [comment]
If you don't create any authorizers, it doesn't wipe out the existing ones, so this works for my purpose but is obviously pretty hacky. Hoping to get time to do this the right way and submit a real PR.

**Pull request closed without merging**
